#!/usr/bin/env bash

# Reproduce the original SEED WebShop experiment (conda env `seed-webshop`: Python 3.10, vllm 0.8.2).
# Thin wrapper: all algorithm / training settings come from SEED's own launchers
# (scripts/sft/webshop/*, examples/seed_trainer/run_webshop_sft_glm_self.sh); nothing from
# the AgentStream configuration (agentstream_full.env, AGENTSTREAM_*) is used.
#
# Usage:
#   [STAGE=all|sft|rl] [METHOD=seed|grpo_sft] [N_GPUS=2] bash examples/seed_trainer/run_webshop_seed_repro.sh [hydra overrides...]
#
#   STAGE=sft  Stage 1: hindsight-skill SFT data (scripts/sft/webshop/prepare_data.sh) + SFT
#              (train_sft.sh); exports $MODELS_ROOT/Qwen2.5-3B-Instruct-webshop-episode-skill-sft-glm-self.
#              Needs the base model $MODELS_ROOT/Qwen2.5-3B-Instruct and OPENAI_* (teacher API) in .env.
#   STAGE=rl   Stage 2: self-evolving OPD RL (run_webshop_sft_glm_self.sh).
#              Needs the Stage-1 checkpoint (or WEBSHOP_RL_MODEL_PATH).
#   STAGE=all  sft, then rl (default). A finished SFT export is skipped.
#
# METHOD selects the RL objective of Stage 2 (both start from the same Stage-1 SFT checkpoint):
#   seed       (default) SEED as published: GRPO outcome advantage + gated OPD loss (coef 0.01) with
#              the policy's own skill analyzer.
#   grpo_sft   the same run without the OPD side: opd_loss_coef=0 and skill analysis off, so only the
#              outcome advantage trains the policy. Everything else (batch, lr, KL, steps, SFT init)
#              is identical, so the pair isolates what OPD adds. It gets its own experiment name /
#              checkpoint directory (grpo_sft_...), so it never resumes the SEED run.
#
# SKIP_PREPARE=true (with STAGE=sft|all) reuses the SFT parquet already generated by an earlier
# run and only redoes SFT training. The expensive part of Stage 1 (baseline rollouts + teacher API
# calls) is not repeated.
#
# WebShop needs three small data files (items_shuffle_1000.json, items_ins_v2_1000.json,
# items_human_ins.json under agent_system/environments/env_package/webshop/webshop/data) and a Lucene
# index built from them (search_engine/convert_product_file_format.py + run_indexing.sh). Both are
# git-ignored; the full 5.5 GB items_shuffle.json that setup.sh -d all downloads is not used. The
# preflight below prints the exact commands when something is missing.
#
# vLLM: prepare_data.sh always starts its policy server with --data-parallel-size, which older vLLM
# builds (e.g. 0.8.2 in seed-webshop) reject. The wrapper probes the vLLM it will use and, if the flag is
# unknown, drops it (the policy server then runs on one GPU). Set VLLM_CONDA_ENV=<env with a newer vLLM>
# to serve the policy from that env with data parallelism instead.
#
# Ray: seed-webshop runs Python 3.10.0, whose asyncio bug crashes Ray's dashboard agent (and with it every
# ray.init in SFT data generation and RL). When the env's Python is exactly 3.10.0 the wrapper puts
# _common/py310_asyncio_fix (a version-gated sitecustomize.py) on PYTHONPATH; the env itself is untouched.
# Upgrading the env's Python to a later 3.10.x makes this unnecessary.
#
# The only deviations from the original scripts: the GPU count (their default is 8) and
# trainer.max_actor_ckpt_to_keep=1 (keep only the latest checkpoint). Extra arguments are hydra
# overrides forwarded to the RL launcher. RL resumes from its latest checkpoint, so re-submitting
# after a walltime kill continues. DRY_RUN=true prints the resolved settings without training.

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

# SEED's launchers source $ENV_FILE themselves. The shared .env is AgentStream-oriented (it pins
# CONDA_ENV=seed-as and many AGENTSTREAM_* switches), so hand them a filtered copy carrying only
# the machine paths and credentials the original scripts read.
SRC_ENV_FILE="${ENV_FILE:-$PROJECT_ROOT/.env}"
SEED_ENV_FILE="$(mktemp)"
trap 'rm -f "$SEED_ENV_FILE" "${VLLM_SHIM:-}"' EXIT
if [[ -f "$SRC_ENV_FILE" ]]; then
    (
        set -a
        # shellcheck disable=SC1090
        source "$SRC_ENV_FILE"
        set +a
        for v in MODELS_ROOT CHECKPOINTS_ROOT TMPDIR RAY_TMPDIR \
                 OPENAI_BASE_URL OPENAI_API_KEY OPENAI_MODEL OPENAI_API_RETRIES OPENAI_API_RETRY_DELAY \
                 WANDB_API_KEY WANDB_MODE HF_TOKEN WEBSHOP_DATA WEBSHOP_DATA_DIR; do
            if [[ -n "${!v:-}" ]]; then printf '%s=%q\n' "$v" "${!v}"; fi
        done
    ) > "$SEED_ENV_FILE"
fi
chmod 600 "$SEED_ENV_FILE"
export ENV_FILE="$SEED_ENV_FILE"
# shellcheck disable=SC1090
set -a; source "$SEED_ENV_FILE"; set +a

export CONDA_ENV="${SEED_CONDA_ENV:-seed-webshop}"
export PYTHONUNBUFFERED=1

# prepare_data.sh binds its policy vLLM server to $HOST, but activating a conda env that ships
# compilers exports HOST=x86_64-conda-linux-gnu, which vLLM cannot bind to. Pin it explicitly.
export HOST="${POLICY_HOST:-127.0.0.1}"

STAGE="${STAGE:-all}"
METHOD="${METHOD:-seed}"
N_GPUS="${N_GPUS:-2}"
: "${MODELS_ROOT:?Please set MODELS_ROOT in .env}"

case "$STAGE" in all|sft|rl) ;; *) echo "Unknown STAGE '$STAGE' (use all | sft | rl)" >&2; exit 2 ;; esac

# The scripts assume 8 GPUs by default; scale every GPU-count knob to what the node has.
export N_GPUS_PER_NODE="$N_GPUS"
export NPROC_PER_NODE="$N_GPUS"
export DATA_PARALLEL_SIZE="${DATA_PARALLEL_SIZE:-$N_GPUS}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-$(seq -s, 0 $((N_GPUS - 1)))}"

if (( $(tr ',' '\n' <<< "$CUDA_VISIBLE_DEVICES" | wc -l) != N_GPUS )); then
    echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES does not list N_GPUS=$N_GPUS devices." >&2
    exit 1
fi

# WebShop product data and search index (git-ignored, see the header). The RL env reads the in-repo
# copy, and Stage-1 data generation needs it too unless it is skipped (SKIP_PREPARE=true).
WEBSHOP_DIR="$PROJECT_ROOT/agent_system/environments/env_package/webshop/webshop"
need_webshop_data=false
if [[ "$STAGE" != sft ]]; then need_webshop_data=true; fi
if [[ "$STAGE" != rl && "${SKIP_PREPARE:-false}" != true ]]; then need_webshop_data=true; fi

webshop_setup_hint() {
    cat >&2 <<HINT
WebShop needs three small data files and a search index built from them. In the $CONDA_ENV env:
  1. put items_shuffle_1000.json, items_ins_v2_1000.json and items_human_ins.json into
     $WEBSHOP_DIR/data
     (setup.sh fetches them with gdown, which Google Drive may refuse; a third-party mirror is
      huggingface-cli download YWZBrandon/webshop-data items_shuffle_1000.json items_ins_v2_1000.json items_human_ins.json --repo-type dataset --local-dir $WEBSHOP_DIR/data)
  2. cd $WEBSHOP_DIR/search_engine && python convert_product_file_format.py && ./run_indexing.sh
HINT
}

if [[ "${DRY_RUN:-false}" != "true" && "$need_webshop_data" == true ]]; then
    for f in data/items_shuffle_1000.json data/items_ins_v2_1000.json data/items_human_ins.json; do
        if [[ ! -f "$WEBSHOP_DIR/$f" ]]; then
            echo "WebShop data missing: $WEBSHOP_DIR/$f" >&2
            webshop_setup_hint
            exit 1
        fi
    done
    # A freshly created index directory only holds segments_N and write.lock.
    if [[ -z "$(find "$WEBSHOP_DIR/search_engine/indexes" -type f ! -name 'segments_*' ! -name write.lock 2>/dev/null | head -n 1)" ]]; then
        echo "WebShop search index is empty: $WEBSHOP_DIR/search_engine/indexes" >&2
        webshop_setup_hint
        exit 1
    fi
fi

# The WebShop RL launcher runs under `set -e` and calls `ulimit -u 65536`, which fails (and aborts the
# run) when the hard process limit is lower.
if [[ "$STAGE" != sft ]]; then
    hard_nproc="$(ulimit -Hu)"
    if [[ "$hard_nproc" != unlimited ]] && (( hard_nproc < 65536 )); then
        echo "Hard process limit is $hard_nproc (< 65536): the WebShop RL launcher's 'ulimit -u 65536' would abort." >&2
        exit 1
    fi
fi

BASE_MODEL="${BASE_MODEL:-$MODELS_ROOT/Qwen2.5-3B-Instruct}"
SFT_MODEL="${WEBSHOP_RL_MODEL_PATH:-${HF_MODEL_PATH:-$MODELS_ROOT/Qwen2.5-3B-Instruct-webshop-episode-skill-sft-glm-self}}"

echo "SEED WebShop reproduction"
echo "  stage:      $STAGE"
echo "  conda env:  $CONDA_ENV"
echo "  GPUs:       $N_GPUS (CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES)"
echo "  base model: $BASE_MODEL"
echo "  SFT model:  $SFT_MODEL"
echo "  method:     $METHOD"

# Hydra overrides that turn the SEED launcher into the chosen RL method. They are appended after
# the launcher's own arguments, so they win (a later override on the command line wins in turn).
case "$METHOD" in
    seed)
        METHOD_OVERRIDES=()
        ;;
    grpo_sft)
        METHOD_OVERRIDES=(actor_rollout_ref.actor.opd_loss_coef=0 algorithm.seed.enable_analysis=False)
        # A separate name keeps checkpoints / wandb run apart; resume_mode=auto would otherwise
        # pick up the SEED run's checkpoint directory.
        export EXPERIMENT_NAME="${EXPERIMENT_NAME:-grpo_sft_qwen2.5_3b_webshop_sft_glm_self_mean-norm}"
        ;;
    *) echo "Unknown METHOD '$METHOD' (use seed | grpo_sft)" >&2; exit 2 ;;
esac
echo "  overrides:  ${METHOD_OVERRIDES[*]:-<none>}"

# Does the vLLM of conda env <env> know --data-parallel-size? Newer builds list it under --help=all
# (plain --help only shows groups); older ones (0.8.x) fail on --help=all and print everything with --help.
# The help text is captured first so that grep -q cannot trip pipefail with a SIGPIPE.
vllm_supports_dp() {
    command -v conda >/dev/null 2>&1 || return 0   # cannot probe: keep the original behaviour
    local help_text
    help_text="$(conda run -n "$1" vllm serve --help=all 2>/dev/null || conda run -n "$1" vllm serve --help 2>/dev/null || true)"
    [[ "$help_text" == *--data-parallel-size* ]]
}

# prepare_data.sh unconditionally passes --data-parallel-size (default 8, an empty value falls back to
# it), so for a vLLM without the flag hand it a launcher that drops the flag.
configure_policy_vllm() {
    if [[ -n "${VLLM_BIN:-}" ]]; then return 0; fi   # caller supplied their own binary
    local vllm_env="${VLLM_CONDA_ENV:-$CONDA_ENV}"
    if vllm_supports_dp "$vllm_env"; then return 0; fi
    echo "[vLLM] the vllm in '$vllm_env' has no --data-parallel-size: dropping it, the policy server runs on one GPU." >&2
    echo "[vLLM] to use all $N_GPUS GPUs set VLLM_CONDA_ENV to an env with a newer vLLM." >&2
    VLLM_SHIM="$(mktemp)"
    cat > "$VLLM_SHIM" <<'SHIM'
#!/usr/bin/env bash
args=()
skip=false
for a in "$@"; do
    if [[ "$skip" == true ]]; then skip=false; continue; fi
    case "$a" in
        --data-parallel-size) skip=true ;;
        --data-parallel-size=*) ;;
        *) args+=("$a") ;;
    esac
done
exec vllm "${args[@]}"
SHIM
    chmod 700 "$VLLM_SHIM"
    export VLLM_BIN="$VLLM_SHIM"
}

# Ray's dashboard agent crashes on Python 3.10.0 (see the header). Detect it in the target env and add the
# fix directory to PYTHONPATH, which the raylet and its agents inherit.
enable_py310_asyncio_fix() {
    command -v conda >/dev/null 2>&1 || return 0   # the launchers need conda anyway
    local ver
    ver="$(conda run -n "$CONDA_ENV" python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))' 2>/dev/null | tail -n 1)"
    if [[ "$ver" == "3.10.0" ]]; then
        export PYTHONPATH="$SCRIPT_DIR/_common/py310_asyncio_fix${PYTHONPATH:+:$PYTHONPATH}"
        echo "[ray] $CONDA_ENV runs Python 3.10.0: enabling the asyncio fix for Ray's dashboard agent."
    fi
}

run_sft() {
    if [[ -f "$SFT_MODEL/config.json" ]]; then
        echo "[SKIP] SFT checkpoint already exists: $SFT_MODEL"
        return 0
    fi
    if [[ ! -f "$BASE_MODEL/config.json" ]]; then
        echo "Base model not found: $BASE_MODEL (set BASE_MODEL)" >&2
        exit 1
    fi
    export MODEL_PATH="$BASE_MODEL"
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        echo "Dry run: would run prepare_data.sh (skipped: ${SKIP_PREPARE:-false}) and train_sft.sh from $BASE_MODEL"
        return 0
    fi
    if [[ "${SKIP_PREPARE:-false}" == "true" ]]; then
        echo "[SKIP] data preparation (SKIP_PREPARE=true): reusing the existing SFT parquet"
    else
        configure_policy_vllm
        bash scripts/sft/webshop/prepare_data.sh
    fi
    bash scripts/sft/webshop/train_sft.sh
}

run_rl() {
    if [[ "${DRY_RUN:-false}" != "true" && ! -f "$SFT_MODEL/config.json" ]]; then
        echo "SFT checkpoint not found: $SFT_MODEL (run STAGE=sft first or set WEBSHOP_RL_MODEL_PATH)" >&2
        exit 1
    fi
    # MODEL_PATH was the SFT base model in stage 1; RL starts from the SFT export.
    unset MODEL_PATH
    export HF_MODEL_PATH="$SFT_MODEL"
    bash examples/seed_trainer/run_webshop_sft_glm_self.sh trainer.max_actor_ckpt_to_keep=1 "${METHOD_OVERRIDES[@]}" "$@"
}

if [[ "${DRY_RUN:-false}" != "true" ]]; then enable_py310_asyncio_fix; fi
if [[ "$STAGE" == all || "$STAGE" == sft ]]; then run_sft; fi
if [[ "$STAGE" == all || "$STAGE" == rl ]]; then run_rl "$@"; fi
echo "Done."
